debug in dependency/debug for all client calls.
masslbs/Tennessine pull request #101
Opened 2024-08-27 16:59 UTC by jchoi330

2024-08-27 17:16 UTC, jchoi330 commented on packages/frontend/tests/CreateStore.test.tsx
this is just test update since we deleted auto fill for base currency

2024-08-27 17:52 UTC, wanderer commented on packages/frontend/src/app/common/components/CurrencyChange.tsx
> +    }
```suggestion
   stateManager.manifest.get()
     .then(shopManifest =>setAcceptedChain(shopManifest.acceptedCurrencies))
     .reject(debug)
```

2024-08-27 17:53 UTC, wanderer requested changes
none of these try catches will work

2024-09-06 17:40 UTC, wanderer commented on packages/frontend/src/app/components/products/VisibilitySlider.tsx
> +        markAsVisible();
```suggestion
        markAsVisible().catch;
```

2024-09-06 17:40 UTC, wanderer commented on packages/frontend/src/app/components/products/VisibilitySlider.tsx
> +    (() => {
```suggestion

```

2024-09-06 17:43 UTC, wanderer approved these changes

2024-09-06 17:43 UTC, merged