design changes
masslbs/Tennessine pull request #117
Opened 2024-10-16 23:59 UTC by jchoi330

2024-11-01 05:53 UTC, jchoi330 commented on packages/frontend/tests/AddProductView.test.tsx
!!! Ignore all frontend tests for now !!! 
Still refactoring them after the relayClient & stateManager export module

2024-11-01 10:54 UTC, jchoi330 commented on packages/client/test/guestCheckout.test.ts
> +      const hash = await guestWallet.writeContract({
need to  circle back to this. payTokenPreApproved fails with unknown custom error right now.

2024-11-01 12:09 UTC, cryptix requested changes
First pass, i want to review the stateManager and context changes more thoroughly once the tests are working again.

2024-11-01 14:44 UTC, wanderer requested changes

2024-11-01 14:44 UTC, wanderer commented on packages/frontend/src/app/store/page.tsx
> +              .then()
you can use promise chaining here, instead of nesting the promeses

2024-11-06 12:51 UTC, cryptix commented
superseeded by devcon-rc1

2024-11-06 12:51 UTC, closed without merging