wip
masslbs/Tennessine pull request #80
Opened 2024-07-18 12:11 UTC by jchoi330

wip

wip

wip

2024-07-18 12:18 UTC, wanderer commented on packages/stateManager/index.ts
> +  abstract createItem(obj: T): Promise<void>;
```suggestion
  abstract create(obj: T): Promise<void>;
```

2024-07-18 12:19 UTC, wanderer commented on packages/stateManager/index.ts
> +  abstract updateItem(obj: T): Promise<void>;
```suggestion
  abstract update(obj: T): Promise<void>;
```

2024-07-18 12:19 UTC, wanderer commented on packages/stateManager/index.ts
> +  abstract getListing(id: string): Promise<any | null>;
```suggestion
  abstract getAll(): Promise<Map<string, Item>>;
  abstract get(id: string): Promise<any | null>;
```

2024-07-18 12:20 UTC, wanderer commented on packages/stateManager/index.ts
> +    await this.db.put(`products-${item.id}`, item);
```suggestion
    await this.db.put(item.id, item);
```

2024-07-19 10:16 UTC, jchoi330 commented on packages/stateManager/index.ts
> +    } else if (event.updateTag) {
we need these tag events in the product sub level since we are adding and removing tags from a product

2024-07-19 12:08 UTC, wanderer reviewed
It would be good to have a comment for each public function that describes what it does.

2024-07-19 12:08 UTC, wanderer commented on packages/stateManager/index.ts
> +  abstract getAll(): T[];
just return iterator

2024-07-19 12:08 UTC, wanderer commented on packages/stateManager/index.ts
> +      const metadata = JSON.parse(new TextDecoder().decode(ci.metadata));
UintArrayToJSON

2024-07-19 12:43 UTC, wanderer requested changes
It would be good to have a comment for each public function that describes what it does.

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +        cs.itemIds.map(async (id: Uint8Array, i: number) => {
forEach not map

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +      return true;
```suggestion

```

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +      return true;
```suggestion
```

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +  async update(
`update` should handle adding and removing tags

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +    const item = await this.db.get(itemId);
do this in parallel with network operation so that when the relay has confirmed the update we will have the data from the db.

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +      await this.client.updateItem({ itemId: hexToBytes(itemId), price });
we should only call `updateItem` once per call to `this.update`

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +      this.client.changeStock({ itemIds: [hexToBytes(itemId)], diffs: [diff] });
we need to wait for this promise to resolve. Ideally this would be done concurrently with `client.updateItem`

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +  getAll() {
should just proxy the iterator.

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +class ShopDetailsManager extends PublicObjectManager<ShopFields> {
Manifest

2024-07-19 12:43 UTC, wanderer commented on packages/stateManager/index.ts
> +  constructor(db: Store<ShopFields>, client: RelayClient) {
```suggestion
  constructor(store: Store<ShopFields>, client: RelayClient) {
```

2024-07-22 14:04 UTC, closed without merging